services:
  spring-user:
    image: spring-user:latest
    container_name: spring-user
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CONFIG_SERVER=${SPRING_CONFIG_SERVER}
      - LOKI_URL="loki"
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
    restart: unless-stopped
    networks:
      - labs
networks:
  labs:
    external: true
