spring:

  # Configurações para o Keycloak Admin API
  keycloak:
    admin:
      client-id: mocked-client
      client-secret: mocked-secret
      auth-server-url: http://localhost:8081
      realm: mocked-realm