server:
  port: 8091

spring:
  application:
    name: spring-user
  config:
    import: optional:configserver:http://${SPRING_CONFIG_SERVER:localhost}:8888  # Config Server opcional

management:
  tracing:
    sampling:
      probability: 1.0  # 100% das requisições serão rastreadas


springdoc:
  api-docs:
    path: /user-docs
  swagger-ui:
    path: /user/swagger-ui.html
  default-produces-media-type: application/json

app:
  version: @project.version@
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
logging:
  level:
    org.springframework.security: INFO
    org.springdoc: debug
    io.opentelemetry.exporter.otlp: DEBUG




