server:
  port: 8091

spring:
  application:
    name: spring-user
  config:
    import: optional:configserver:http://${SPRING_CONFIG_SERVER:localhost}:8888  # Config Server opcional

management:
  tracing:
    sampling:
      probability: 1.0  # 100% das requisições serão rastreadas
  otlp:
    tracing:
      endpoint: http://otel-collector:4318  # Enviar apenas traces via HTTP
      enabled: true
    logging:
      export:
        enabled: false

springdoc:
  api-docs:
    path: /user/api-docs
  swagger-ui:
    path: /user/swagger-ui.html
  default-produces-media-type: application/json

app:
  version: @project.version@

logging:
  level:
    org.springframework.security: INFO
    org.springdoc: debug
    io.opentelemetry.exporter.otlp: DEBUG




